export component MainWindow inherits Window {
    width: 400px;
    height: 300px;
    HorizontalLayout {
        spacing: 5px; // 元素之间的距离
        //padding: 10px; // 内边距
        //padding-left: 20px; // 左内边距
        width: 100%; // 占满父级宽度
        height: 100%; // 占满父级高度
        x: 0px;
        y: 0px;
        //alignment: center; // 居中对齐
        //alignment: start; // 起始元素对齐
        //alignment: end; // 结束元素对齐
        //alignment: space-between; // 元素之间平均分布
        //alignment: space-around; // 元素之间平均分布，且两端有一半的间距
        //alignment: space-evenly; // 元素之间平均分布，且两端有相同的间距
    
        Rectangle { background: red; width:50px; height: 30px; }
        Rectangle { background: green; width:100px; height: 30px; }
        Rectangle { background: blue; width:50px; height: 80px; }
    }
}
