import { Button } from "std-widgets.slint";

export component MainWindow inherits Window {
    width: 400px;
    height: 200px;
    VerticalLayout {
        input := Text {
            text: "input text";
        }

        HorizontalLayout {
            spacing: 10px; //按钮之间的间距
            Button {
                width: 100px;
                height: 40px;
                text: "click"; //按钮文本
                //text: "修改文本";
                //checkable: true; //按钮是否可选中
                //checked: true; //按钮是否选中
                //enabled: false; //按钮是否可用
                //icon: @image-url("assets/icon.png"); //按钮图标
                //icon-size: 50px; //图标大小
                //colorize-icon: true; //图标是否随按钮文本颜色变化
                //primary: true; //是否应用主要强调色样式
                clicked => {
                    input.text = "text changed"; //修改文本
                }
            }

            Button {
                width: 100px;
                height: 40px;
                text: "cancel";
            }

            Button {
                width: 100px;
                height: 40px;
                text: "ok";
            }
        }
    }
}
