export component MainWindow inherits Window {
    width: 400px;
    height: 300px;
    GridLayout {
        spacing: 5px; // 元素之间的距离
        spacing-horizontal: 10px; // 水平元素之间的距离
        //spacing-vertical: 10px; // 垂直元素之间的距离
        //padding: 10px; // 内边距
        //padding-left: 20px; // 左内边距
        width: 100%; // 占满父级宽度
        height: 100%; // 占满父级高度
        x: 0px;
        y: 0px;
    
        //第一行
        Rectangle { background: red; width:50px; height: 30px; }
        Rectangle { background: green; width:100px; height: 30px; }
        Rectangle { background: blue; width:50px; height: 80px; }

        //第二行
        Rectangle { background: red; width:50px; height: 30px; row: 1; col: 0; }
        Rectangle { background: green; width:100px; height: 30px; row: 1; col: 1; }
        Rectangle { background: blue; width:50px; height: 80px; row: 1; col: 2; }

        //第三行
        //Rectangle { background: red; width:50px; height: 30px; row: 2; col: 0; }
        Rectangle { background: green; width:300px; height: 30px; row: 2; col: 1; colspan: 2; }

        //第四行
        Rectangle { background: red; width:50px; height: 100px; row: 2; col: 0;  rowspan: 2; }
        Rectangle { background: green; width:100px; height: 30px; row: 3; col: 1; }
        Rectangle { background: blue; width:50px; height: 80px; row: 3; col: 2; }
    }
}
