import { SpinBox } from "std-widgets.slint";

export component MainWindow inherits Window {
    width: 400px;
    height: 200px;
    SpinBox {
        width: 90%;
        height: 30px;
        value: 50; //微调框的当前值 默认值为0
        maximum: 100; //微调框的最大值 默认值为100
        minimum: 0; //微调框的最小值 默认值为0
        //read-only: true; //是否只读 默认值为false
        step-size: 5; //微调框的步长 默认值为1 不能为小数
        horizontal-alignment: left; //水平对齐方式 可选值为left、center、right、start（文字方向的起始位置）、end（文字方向的结束位置） 默认值为left
        edited(value) => { //当微调框的值被编辑时触发的事件，参数value为当前的值
            debug("New value: ", value);
        }
    }
}
