export component MainWindow inherits Window {
    width: 400px;
    height: 200px;
    TextInput {
        text: "中国"; // 设置文本内容
        //text: "hello world"; // 设置文本内容
        color: red; // 设置文本颜色
        font-family: "Microsoft YaHei"; // 设置字体
        font-size: 24px; // 设置字体大小
        //font-weight: 800; // 设置字体加粗
        //font-italic: true; // 设置字体斜体
        horizontal-alignment: center; // 设置水平对齐方式为居中
        vertical-alignment: center; // 设置垂直对齐方式为居中
        //horizontal-alignment: left; // 设置水平对齐方式为左对齐
        //vertical-alignment: top; // 设置垂直对齐方式为顶部对齐
        //horizontal-alignment: right; // 设置水平对齐方式为右对齐
        //vertical-alignment: bottom; // 设置垂直对齐方式为底部对
        //input-type: text; // 设置输入类型为文本
        //input-type: password; // 设置输入类型为密码
        //input-type: number; // 设置输入类型为数字
        //input-type: decimal; // 设置输入类型为小数
        //letter-spacing: 10px; // 设置字符间距
        //page-height: 30px; // 页面的高度用于计算当用户按页上或页下时滚动的距离
        //read-only: true; // 设置为只读模式
        //selection-background-color: red; // 设置选中文本的背景颜色
        //selection-foreground-color: black; // 设置选中文本的颜色
        //single-line: false; // 设置单行输入模式
        //text-cursor-width: 10px; // 设置光标宽度
        //wrap: no-wrap; // 设置文本自动换行
        //wrap: word-wrap; // 设置文本自动换行，单词换行
        //wrap: char-wrap; // 设置文本自动换行，字符换行
    }
}
