import { ScrollView } from "std-widgets.slint";

export component MainWindow inherits Window {
    width: 400px;
    height: 200px;
    ScrollView {
        width: 200px; //滚动视图的宽度
        height: 200px; //滚动视图的高度
        //viewport-x: -50px; //滚动视图相对于视口的 x 位置, 通常是一个负值
        //viewport-y: -50px; //滚动视图相对于视口的 y 位置, 通常是一个负值
        viewport-width: 300px; //滚动视口的宽度
        viewport-height: 300px; //滚动视口的高度
        //enabled: false; //是否启用滚动视图 默认值为true
        //vertical-scrollbar-policy: always-off; //禁用垂直滚动条
        //vertical-scrollbar-policy: as-needed; //根据需要显示垂直滚动条 默认值
        //vertical-scrollbar-policy: always-on; //始终显示垂直滚动条
        //horizontal-scrollbar-policy: as-needed; //根据需要显示水平滚动条 默认值
        //horizontal-scrollbar-policy: always-off; //禁用水平滚动条
        //horizontal-scrollbar-policy: always-on; //始终显示水平滚动条
       
        Rectangle {
            width: 30px;
            height: 30px;
            x: 275px;
            y: 50px;
            background: blue;
        }

        Rectangle {
            width: 30px;
            height: 30px;
            x: 175px;
            y: 130px;
            background: red;
        }

        Rectangle {
            width: 30px;
            height: 30px;
            x: 25px;
            y: 210px;
            background: yellow;
        }

        Rectangle {
            width: 30px;
            height: 30px;
            x: 98px;
            y: 55px;
            background: orange;
        }

        scrolled() => {
            //当滚动视图被滚动时触发
        debug("viewport-x: ", self.viewport-x);
            debug("viewport-y: ", self.viewport-y);
        }
    }
}
