import { TabWidget } from "std-widgets.slint";

export component MainWindow inherits Window {
    width: 400px;
    height: 200px;
    TabWidget {
        //current-index: 0; // 当前选中的标签索引，默认为0
        orientation: Orientation.vertical; // 标签排列方向，默认为horizontal(水平) vertical（垂直）
        Tab {
            //title: "标\n签\n组\n件\n1";
            title: "标签组件1"; // 标签标题，可以包含换行符\n来实现多行显示
            Rectangle {
                width: 100%;
                height: 100%;
                background: #f0f0f0;
            }
        }
        Tab {
            //title: "标\n签\n组\n件\n2";
            title: "标签组件2";
            Rectangle {
                width: 100%;
                height: 100%;
                background: #e0e0e0;
            }
        }
    }
}
