export component MainWindow inherits Window {
    in-out property <string> content;
    width: 400px;
    height: 400px;
    Text {
        //text: content;
        text: "Hello World"; //Text显示内容
        color: #3586f4; //字体颜色
        //font-family: "Microsoft YaHei"; //字体
        font-size: 30px; //字体大小
        //font-weight: 800; //字体加粗 取值范围100-900，数值越大越粗 400为正常字体
        //font-italic: true; //字体斜体
        //horizontal-alignment: center; //水平对齐方式
        //vertical-alignment: center; //垂直对齐方式
        //letter-spacing: 10px; //字母间距
        //overflow: clip; //文本溢出时的处理方式，裁剪
        //overflow: elide; //文本溢出时的处理方式，省略号
        //text: "Hello World,Hello World,Hello World";
        //width: 200px;
        //wrap: no-wrap; //文本换行，不换行
        //wrap: word-wrap; //文本换行，单词内换行
        //wrap: char-wrap; //文本换行，字符内换行
        //stroke: #ff0000; //文本描边颜色
        //stroke-width: 2px; //文本描边宽度
        //stroke-style: outside; //文本描边样式 在文本外侧描边
        //stroke-style: center; //文本描边样式 在文本中心描边
    }
}
