import { ListView } from "std-widgets.slint";

export component MainWindow inherits Window {
    width: 400px;
    height: 200px;
    ListView {
        width: 100px; //列表视图的宽度
        height: 100%; //列表视图的高度
        enabled: true; //是否启用列表视图 默认值为true
        //vertical-scrollbar-policy: always-off; //禁用垂直滚动条
        //vertical-scrollbar-policy: as-needed; //根据需要显示垂直滚动条 默认值
        //vertical-scrollbar-policy: always-on; //始终显示垂直滚动条
         for data in [
            { text: "Blue11111111111111aaaaaaaaaa", color: #0000ff, bg: #eeeeee },
            { text: "Red", color: #ff0000, bg: #eeeeee },
            { text: "Green", color: #00ff00, bg: #eeeeee },
            { text: "Yellow", color: #ffff00, bg: #222222 },
            { text: "Black", color: #000000, bg: #eeeeee },
            { text: "White", color: #ffffff, bg: #222222 },
            { text: "Magenta", color: #ff00ff, bg: #eeeeee },
            { text: "Cyan", color: #00ffff, bg: #222222 },
        ]: Rectangle {
            height: 30px;
            background: data.bg;
            width: parent.width;
            Text {
                x: 0;
                text: data.text;
                color: data.color;
            }
        }

        scrolled() => { //当列表视图被滚动时触发
            debug("viewport-x: ", self.viewport-x);
            debug("viewport-y: ", self.viewport-y);
        }
    }
}
